Try {{ try_number }} out of {{ max_tries + 1 }}<br>
Docker exception:<br>{{ exception_html }}<br>
<a href="{{ ti.log_url }}">Open log in browser</a><br>
Log path on server: {{ ti.log_filepath }}<br>